language: rust
notifications:
  email:
    on_success: never
    on_failure: always
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache:
  directories:
  - /home/travis/.cargo

before_script:
- rm -rf /home/travis/.cargo/registry
- rustup update nightly
- rustup component add rustfmt-preview clippy-preview --toolchain nightly
script:
- cargo +nightly fmt --all -- --check
- cargo +nightly clippy
- cargo test --verbose --all