language: rust
notifications:
  notifications:
    on_success: never
    on_failure: always
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - rustup update nightly
  - rustup component add rustfmt-preview --toolchain nightly
script:
  - cargo +nightly fmt --all -- --check
  - cargo test --verbose --all
addons:
  apt:
    update: true