[package]
name = "basic"
version = "0.1.0"
authors = ["DCjanus <DCjanus@dcjanus.com>"]

[lib]
proc-macro = true

[dependencies]
proc_macro_helper = { path = "../../" }
quote = "0.6"
syn = { version = "0.15", features = ["extra-traits"] }
